# -*- coding: utf-8 -*-
"""modelo app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAfj46rtgVYmvBRAWYYW4dQrfeL9smfl
"""

# Importar librerías
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib



df = pd.read_csv("/content/student_lifestyle_100k.csv")

df["Department"] = df["Department"].astype(str)

df["Department"] = df["Department"].str.strip().str.lower()

df.loc[df["Department"] == "engineering", "Department"] = 0
df.loc[df["Department"] == "science", "Department"] = 1
df.loc[df["Department"] == "arts", "Department"] = 2
df.loc[df["Department"] == "business", "Department"] = 3
df.loc[df["Department"] == "medical", "Department"] = 4

df["Department"] = df["Department"].astype(int)

df.drop(columns=["Student_ID"], inplace=True)

df["Gender"] = df["Gender"].astype(str)

df["Gender"] = df["Gender"].str.strip().str.lower()

df.loc[df["Gender"] == "male", "Gender"] = 0
df.loc[df["Gender"] == "female", "Gender"] = 1

df["Gender"] = df["Gender"].astype(int)
# Ver primeras filas
print(df.head())



y = df["Depression"]

# X = todas las columnas menos la salida
X = df.drop(columns=["Depression"])



X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    alpha=0.0001,
    learning_rate_init=0.001,
    max_iter=500,
    early_stopping=True,
    random_state=42
)



model.fit(X_train, y_train)



score = model.score(X_test, y_test)

print(f'Accuracy: {score:.4f}')



joblib.dump(model, "modelo.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Modelo y scaler guardados correctamente")

#falta balancearlo
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Predicciones
y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print("Matriz de confusión:")
print(cm)

# Graficar matriz
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicción")
plt.ylabel("Valor real")
plt.title("Matriz de Confusión")
plt.show()

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

print("\nDistribución de clases en todo el dataset:")
print(df["Depression"].value_counts())

print("\nDistribución porcentual:")
print(df["Depression"].value_counts(normalize=True) * 100)